import { Link } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";

const colors = {
  indigo: "bg-[#64748b]", // soft indigo
  indigoLight: "bg-[#cbd5e1]",
  green: "bg-emerald-600",
  greenLight: "bg-[#a3d9a5]",
  yellow: "bg-[#facc15]",
  yellowLight: "bg-[#fef3c7]",
  grayTextDark: "text-[#1e293b]",
  grayTextMedium: "text-[#475569]",
  grayBackground: "bg-[#f1f5f9]",
};

function ScrollableStats() {
  const stats = [
    { title: "Active Clients", value: "18,765", icon: "👥", color: colors.indigo },
    { title: "Monthly Revenue", value: "$1.2M", icon: "💰", color: colors.green },
    { title: "Fees Saved", value: "$42,679", icon: "💸", color: colors.yellow },
    { title: "Cash Flow Health", value: "Good", icon: "📈", color: colors.greenLight },
  ];
  return (
    <div
      className={`max-w-7xl mx-auto flex gap-6 overflow-x-auto p-6 scrollbar-thin scrollbar-thumb-gray-300 rounded-b-3xl ${colors.grayBackground}`}
      style={{ WebkitOverflowScrolling: "touch" }}
    >
      {stats.map(({ title, value, icon, color }) => (
        <div
          key={title}
          className={`${color} min-w-[14rem] sm:min-w-[16rem] md:min-w-[18rem] rounded-3xl p-6 text-white drop-shadow-lg flex flex-col shadow-lg flex-shrink-0`}
        >
          <div className="text-4xl">{icon}</div>
          <h3 className="mt-4 font-bold text-xl">{title}</h3>
          <div className="mt-2 text-3xl font-extrabold">{value}</div>
        </div>
      ))}
    </div>
  );
}

function HeroStatCard() {
  return (
    <div className="max-w-7xl mx-auto mt-12 flex flex-col lg:flex-row shadow-lg overflow-hidden rounded-tl-3xl">
      <div
        className={`flex-1 bg-gradient-to-tr from-emerald-600 to-emerald-400 p-8 lg:p-12 text-white`}
      >
        <div className="uppercase mb-4 text-sm tracking-wide font-semibold opacity-75">
          Total Cash Managed
        </div>
        <div className="text-4xl sm:text-6xl font-extrabold">$9.8M</div>
        <div className="mt-4 text-lg opacity-90 max-w-lg">
          Projected net inflow for next quarter based on current trends.
        </div>
        <Link
          to="/upload"
          className="inline-block mt-10 px-6 py-3 bg-slate-700 text-white font-medium rounded-full shadow-lg hover:shadow-2xl hover:scale-105 transition duration-300"
        >
          Upload New Data
        </Link>
      </div>
      <div className="flex-2 p-8 lg:p-12 bg-gradient-to-br from-emerald-400 to-emerald-600 justify-center rounded-tr-3xl text-center">
        <div className={`text-white text-3xl font-semibold `}>
          Detailed Insights
        </div>
        <p className={"text-center text-white text-xl mt-2"}>
          Get smart recommendations and alerts generated by advanced AI analysis
          of your cash flow.
        </p>
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-3 gap-8">
          <div className="flex flex-col items-center gap-2">
            <div className="bg-[#cbd5e1] text-[#64748b] rounded-lg p-3 text-2xl">💡</div>
            <div className={`font-bold text-white`}>DSO Optimized</div>
            <div className={`font-medium text-white`}>
              Reduce days sales outstanding by 7%.
            </div>
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="bg-[#a3d9a5] text-[#2dc44f] rounded-lg p-3 text-2xl">🔄</div>
            <div className={`text-white font-bold`}>Payment Rail Savings</div>
            <div className={`text-white text-sm`}>
              Cut payment fees by 15% using AI recommendations.
            </div>
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="bg-[#fef3c7] text-[#facc15] rounded-lg p-3 text-2xl">📈</div>
            <div className={`text-white font-bold`}>Cash Position Forecast</div>
            <div className={`text-white text-sm`}>
              Maintain healthy liquidity buffers one month ahead.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function WidgetGrid() {
  const widgets = [
    {
      title: "Overdue Receivables",
      value: "$34,200",
      description: "Amount currently overdue from clients, impacting cash flow.",
      icon: "📅",
    },
    {
      title: "Upcoming Payables",
      value: "$19,450",
      description: "Bills and payments due in the next 30 days.",
      icon: "💳",
    },
    {
      title: "Cash Conversion Cycle",
      value: "52 days",
      description: "Average days to convert inventory and receivables into cash.",
      icon: "⏳",
    },
    {
      title: "Liquidity Buffer",
      value: "$250,000",
      description: "Cash reserve set aside for unexpected needs.",
      icon: "🛡️",
    },
    {
      title: "Payment Rail Savings",
      value: "$7,820 this month",
      description: "Fees saved using optimized payment methods.",
      icon: "💸",
    },
    {
      title: "Forecast Accuracy",
      value: "93%",
      description: "Accuracy percentage of cash flow forecasts over last quarter.",
      icon: "🔮",
    },
  ];

  return (
    <div className="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 px-6 mt-16">
      {widgets.map(({ title, value, description, icon }, i) => (
        <div key={i} className="bg-white rounded-xl p-6 shadow-md hover:shadow-xl transition transform hover:-translate-y-1 cursor-pointer">
          <div className="text-3xl mb-4">{icon}</div>
          <h3 className="font-semibold mb-1 text-lg text-gray-800">{title}</h3>
          <p className="text-xl font-bold mb-2 text-gray-900">{value}</p>
          <p className="text-gray-600">{description}</p>
        </div>
      ))}
    </div>
  );
}


export default function Dashboard() {
  return (
    <div className="min-h-screen bg-slate-200 ">
      <Header />
      <Sidebar />
      <HeroStatCard />
      <ScrollableStats />
      <WidgetGrid />
    </div>
  );
}

